name: Generate Subtitles

on:
  workflow_dispatch:
    inputs:
      video-id:
        description: 'The video id to process'
        required: false
        default: ''
  schedule:
  - cron: '0 16 * * 5,6,7'

permissions:
  id-token: write
  contents: write

defaults:
  run:
    working-directory: SubtitleConverter

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: dotnet publish
      run: |
        dotnet publish -o publish .\Keboo.Editor\Keboo.Editor.csproj

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Run
      if: ${{ inputs.video-id != '' }}
      run: ./publish/Keboo.Editor.exe youtube subtitles --video-id ${{ inputs.video-id }} --output-directory ../Subtitles
      continue-on-error: true

    - name: Run
      if: ${{ inputs.video-id == '' }}
      run: ./publish/Keboo.Editor.exe youtube subtitles --all --output-directory ../Subtitles
      continue-on-error: true
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'Updating subtitle file(s)'
